apiVersion: v1
kind: Namespace
metadata:
  name: db
  labels:
    id: c0911147
    app: mariadb
    env: dev
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: db
  labels:
    id: c0911147
    app: mariadb
    env: dev
type: Opaque
data:
  root-password: cGFzc3dvcmQ=
  wp-password: cGFzc3dvcmQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: db
  labels:
    id: c0911147
    app: mariadb
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      id: c0911147
  template:
    metadata:
      labels:
        id: c0911147
        app: mariadb
        env: dev
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.5
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: root-password
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wpuser
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: wp-password
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: db
  labels:
    id: c0911147
    app: mariadb
    env: dev
spec:
  selector:
    id: c0911147
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306

