---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: proxy
  labels:
    id: c0911147
    app: nginx-proxy
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      id: c0911147
  template:
    metadata:
      labels:
        id: c0911147
        app: nginx-proxy
        env: dev
    spec:
      containers:
      - name: nginx
        image: karthik8898/nginx-proxy:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: proxy
  labels:
    id: c0911147
    app: nginx-proxy
    env: dev
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    id: c0911147