apiVersion: v1
kind: Namespace
metadata:
  name: proxy
  labels:
    id: c0911147
    app: nginx-proxy
    env: dev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: proxy
  labels:
    id: c0911147
    app: nginx-proxy
    env: dev
data:
  default.conf: |
    server {
      listen 80;
      location / {
        proxy_pass http://wordpress.wp.svc.cluster.local:80;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-Host $host;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: proxy
  labels:
    id: c0911147
    app: nginx-proxy
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      id: c0911147
  template:
    metadata:
      labels:
        id: c0911147
        app: nginx-proxy
        env: dev
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: proxy
  labels:
    id: c0911147
    app: nginx-proxy
    env: dev
spec:
  type: LoadBalancer
  selector:
    id: c0911147
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

