apiVersion: v1
kind: Namespace
metadata:
    name: db
    labels:
        id: c091147
        env: dev
        app: mariadb
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/docker2gcp/locations/northamerica-northeast2/keyRings/my-keyring/cryptoKeys/my-keyring-sw
          created_at: "2024-11-16T17:15:18Z"
          enc: CiQAao0AaIiXIcnCxspT3n/PEUC2pFLsqGc3UL4e/j8ULffCof8SSQCsaSk3z6aQtXw+/HrFP/eETaG7xT90dmHd2p2MLVGDnDO+5vZukTcMiljDANKI3mYuBC75V3eJmOBiQU2GUV9AvJDwTjmfrbA=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-16T17:15:19Z"
    mac: ENC[AES256_GCM,data:ZEX14nDBZsz/iJCdWf8oQhuTXeWAH9+sl9T9pwvGa4HCclwS/Gbl1bWkVeYlrmD0kMN/sc+Z4oVcEAPeeMB5z2qKFEG2vHqgMdHQ+0pnl6bzzNlzFDCvXxeV7D1CUn4dN6raiAoD9i+TM93kRZcThrsBznoEnBrYaYXcio/Kiuc=,iv:HuEXODCAHJ2SNbwVDZySL/EnXkdMXjxBtVnQbzF0uhk=,tag:RbZCGbnyeyNwo6svJahbiw==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: mariadb-secret
    namespace: db
    labels:
        id: c091147
        env: dev
        app: mariadb
type: Opaque
data:
    mariadb-root-password: ENC[AES256_GCM,data:tnGORTy9mEorc8jN/CiA2g==,iv:cZDz5ZSaU2sgvLWoX/o7WtOWhSZzbk+Ec5zMG9mMckQ=,tag:v2PI31hFgD3UhuGuBcw1Jw==,type:str]
    mariadb-password: ENC[AES256_GCM,data:OK9T6r7rw7bsxD9s,iv:Y4nprS60LVH6Q2zP+6Yvzpl9Uv7kBCZXRFaFuJnLFX8=,tag:SQ9NjXBjPcXgsIIdn4ahuw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/docker2gcp/locations/northamerica-northeast2/keyRings/my-keyring/cryptoKeys/my-keyring-sw
          created_at: "2024-11-16T17:15:18Z"
          enc: CiQAao0AaIiXIcnCxspT3n/PEUC2pFLsqGc3UL4e/j8ULffCof8SSQCsaSk3z6aQtXw+/HrFP/eETaG7xT90dmHd2p2MLVGDnDO+5vZukTcMiljDANKI3mYuBC75V3eJmOBiQU2GUV9AvJDwTjmfrbA=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-16T17:15:19Z"
    mac: ENC[AES256_GCM,data:ZEX14nDBZsz/iJCdWf8oQhuTXeWAH9+sl9T9pwvGa4HCclwS/Gbl1bWkVeYlrmD0kMN/sc+Z4oVcEAPeeMB5z2qKFEG2vHqgMdHQ+0pnl6bzzNlzFDCvXxeV7D1CUn4dN6raiAoD9i+TM93kRZcThrsBznoEnBrYaYXcio/Kiuc=,iv:HuEXODCAHJ2SNbwVDZySL/EnXkdMXjxBtVnQbzF0uhk=,tag:RbZCGbnyeyNwo6svJahbiw==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.1
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: mariadb-config
    namespace: db
    labels:
        id: c091147
        env: dev
        app: mariadb
data:
    database-name: ENC[AES256_GCM,data:2yMfbcPStUGE,iv:/S+vJAatayQemRUBhbxUh+k5ALZnYOl1i9vM1E463SM=,tag:Vdm/z5KacjSSn32FCSE4mA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/docker2gcp/locations/northamerica-northeast2/keyRings/my-keyring/cryptoKeys/my-keyring-sw
          created_at: "2024-11-16T17:15:18Z"
          enc: CiQAao0AaIiXIcnCxspT3n/PEUC2pFLsqGc3UL4e/j8ULffCof8SSQCsaSk3z6aQtXw+/HrFP/eETaG7xT90dmHd2p2MLVGDnDO+5vZukTcMiljDANKI3mYuBC75V3eJmOBiQU2GUV9AvJDwTjmfrbA=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-16T17:15:19Z"
    mac: ENC[AES256_GCM,data:ZEX14nDBZsz/iJCdWf8oQhuTXeWAH9+sl9T9pwvGa4HCclwS/Gbl1bWkVeYlrmD0kMN/sc+Z4oVcEAPeeMB5z2qKFEG2vHqgMdHQ+0pnl6bzzNlzFDCvXxeV7D1CUn4dN6raiAoD9i+TM93kRZcThrsBznoEnBrYaYXcio/Kiuc=,iv:HuEXODCAHJ2SNbwVDZySL/EnXkdMXjxBtVnQbzF0uhk=,tag:RbZCGbnyeyNwo6svJahbiw==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mariadb
    namespace: db
    labels:
        id: c091147
        env: dev
        app: mariadb
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mariadb
            id: c091147
            env: dev
    template:
        metadata:
            labels:
                app: mariadb
                id: c091147
                env: dev
        spec:
            containers:
                - name: mariadb
                  image: mariadb:10.5
                  env:
                    - name: MARIADB_ROOT_PASSWORD
                      valueFrom:
                        secretKeyRef:
                            name: mariadb-secret
                            key: mariadb-root-password
                    - name: MARIADB_DATABASE
                      valueFrom:
                        configMapKeyRef:
                            name: mariadb-config
                            key: database-name
                    - name: MARIADB_PASSWORD
                      valueFrom:
                        secretKeyRef:
                            name: mariadb-secret
                            key: mariadb-password
                  ports:
                    - containerPort: 3306
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/docker2gcp/locations/northamerica-northeast2/keyRings/my-keyring/cryptoKeys/my-keyring-sw
          created_at: "2024-11-16T17:15:18Z"
          enc: CiQAao0AaIiXIcnCxspT3n/PEUC2pFLsqGc3UL4e/j8ULffCof8SSQCsaSk3z6aQtXw+/HrFP/eETaG7xT90dmHd2p2MLVGDnDO+5vZukTcMiljDANKI3mYuBC75V3eJmOBiQU2GUV9AvJDwTjmfrbA=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-16T17:15:19Z"
    mac: ENC[AES256_GCM,data:ZEX14nDBZsz/iJCdWf8oQhuTXeWAH9+sl9T9pwvGa4HCclwS/Gbl1bWkVeYlrmD0kMN/sc+Z4oVcEAPeeMB5z2qKFEG2vHqgMdHQ+0pnl6bzzNlzFDCvXxeV7D1CUn4dN6raiAoD9i+TM93kRZcThrsBznoEnBrYaYXcio/Kiuc=,iv:HuEXODCAHJ2SNbwVDZySL/EnXkdMXjxBtVnQbzF0uhk=,tag:RbZCGbnyeyNwo6svJahbiw==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.1
---
apiVersion: v1
kind: Service
metadata:
    name: mariadb
    namespace: db
    labels:
        id: c091147
        env: dev
        app: mariadb
spec:
    type: LoadBalancer
    ports:
        - port: 3306
          targetPort: 3306
    selector:
        app: mariadb
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/docker2gcp/locations/northamerica-northeast2/keyRings/my-keyring/cryptoKeys/my-keyring-sw
          created_at: "2024-11-16T17:15:18Z"
          enc: CiQAao0AaIiXIcnCxspT3n/PEUC2pFLsqGc3UL4e/j8ULffCof8SSQCsaSk3z6aQtXw+/HrFP/eETaG7xT90dmHd2p2MLVGDnDO+5vZukTcMiljDANKI3mYuBC75V3eJmOBiQU2GUV9AvJDwTjmfrbA=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-16T17:15:19Z"
    mac: ENC[AES256_GCM,data:ZEX14nDBZsz/iJCdWf8oQhuTXeWAH9+sl9T9pwvGa4HCclwS/Gbl1bWkVeYlrmD0kMN/sc+Z4oVcEAPeeMB5z2qKFEG2vHqgMdHQ+0pnl6bzzNlzFDCvXxeV7D1CUn4dN6raiAoD9i+TM93kRZcThrsBznoEnBrYaYXcio/Kiuc=,iv:HuEXODCAHJ2SNbwVDZySL/EnXkdMXjxBtVnQbzF0uhk=,tag:RbZCGbnyeyNwo6svJahbiw==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.1
